
# https://rust-lang.github.io/rustfmt
# Max width of a line before wrapping
max_width = 80

# Tabs or spaces?
hard_tabs = false
tab_spaces = 4

# How aggressively to squeeze small items onto one line
use_small_heuristics = "Max"

# Align struct fields if there’s at most this many
struct_field_align_threshold = 20

# Keep imports grouped
merge_imports = true

# Preserve newlines inside function calls if they already exist
preserve_try_format = true

# Format code in doc comments + examples
format_code_in_doc_comments = true

wrap_comments = true
comment_width = 100
imports_granularity = "Crate"
imports_layout = "Vertical"
fn_args_layout = "Vertical"
attr_fn_like_width = 70
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
format_strings = true
